CoursesStore/Controllers/CoursesController.cs
using Braintree;
using CoursesStore.Data;
using CoursesStore.Models;
using CoursesStore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Net.Mail;

namespace CoursesStore.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CoursesStoreContext _context;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly IBraintreeService _braintreeService;
        private readonly IConfiguration _config;

        public CoursesController(IConfiguration config, CoursesStoreContext context, IWebHostEnvironment appEnvironment, IBraintreeService braintreeService)
        {
            _context = context;
            _appEnvironment = appEnvironment;
            _braintreeService = braintreeService;
            _config = config;
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
            }

            var courses = from m in _context.Course
                          select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(s => s.Name!.Contains(searchString));
            }

            return View(await courses.ToListAsync());
        }

        public async Task<IActionResult> PurchaseCreate(int id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var gateway = _braintreeService.GetGateway();
            var clientToken = gateway.ClientToken.Generate();
            ViewBag.ClientToken = clientToken;

            var course = await _context.Course.FirstOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            var coursePurchaseVM = new CoursePurchaseVM
            {
                Id = course.Id,
                Name = course.Name,
                Description = course.Description,
                Price = course.Price,
                EffectCount = course.EffectCount,
                Nonce = "",
                Email = ""
            };

            return View(coursePurchaseVM);
        }

        [HttpPost]
        public IActionResult OrderProcessing(CoursePurchaseVM model)
        {
            var gateway = _braintreeService.GetGateway();
            var request = new TransactionRequest
            {
                Amount = Convert.ToDecimal(Convert.ToInt32(model.Price)),
                PaymentMethodNonce = model.Nonce,
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                }
            };

            Result<Transaction> result = gateway.Transaction.Sale(request);

            if (result.IsSuccess())
            {
                EmailNewsletter.SendEmail(_config.GetValue<string>("EmailConfig:FromAddress"), _config.GetValue<string>("EmailConfig:FromAppPassword"), model.Email, model).GetAwaiter();

                return View("PurchaseSuccess");
            }
            else
            {
                return View("PurchaseFailure");
            }
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [Authorize]
        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Course course)
        {
            if (ModelState.IsValid)
            {
                var graphics = new IFormFile[] { 
                    course.PreviewImage, 
                    course.MainVideo, 
                    course.CardVideo, 
                    course.BeforeExampleImage, 
                    course.AfterExampleImage
                };

                foreach (var item in graphics)
                {
                    if (item != null)
                    {
                        string uploadsFolder = Path.Combine(_appEnvironment.WebRootPath, "Graphics", "Course", course.Name);
                        string uniqueFileName = item.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                        if (!Directory.Exists(uploadsFolder))
                        {
                            Directory.CreateDirectory(uploadsFolder);
                        }

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await item.CopyToAsync(fileStream);
                        }
                    }
                }
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [Authorize]
        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var graphics = new IFormFile[] {
                    course.PreviewImage,
                    course.MainVideo,
                    course.CardVideo,
                    course.BeforeExampleImage,
                    course.AfterExampleImage
                };

                foreach (var item in graphics)
                {
                    if (item != null)
                    {
                        string uploadsFolder = Path.Combine(_appEnvironment.WebRootPath, "Graphics", "Course", course.Name);
                        string uniqueFileName = item.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                        if (!Directory.Exists(uploadsFolder))
                        {
                            Directory.CreateDirectory(uploadsFolder);
                        }

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await item.CopyToAsync(fileStream);
                        }
                    }
                }

                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'CoursesStoreContext.Course'  is null.");
            }
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        private bool CourseExists(int id)
        {
            return (_context.Course?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private class EmailNewsletter
        {

CoursesStore/Views/Courses/Create.cshtml
@model CoursesStore.Models.Course

@{
    ViewData["Title"] = "Create";
}


<div class="row container-fluid">
    <div class="col-md-5">
        <h1>Create</h1>
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.AntiForgeryToken()
            <div class="form-group mb-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="EffectCount" class="control-label"></label>
                <input asp-for="EffectCount" class="form-control" />
                <span asp-validation-for="EffectCount" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label class="control-label">Preview Image</label>
                <input type="file" name="PreviewImage" accept=".jpg, .jpeg, .png" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label class="control-label">Main Video</label>
                <input type="file" name="MainVideo" accept=".mp4" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label class="control-label">Card Video</label>
                <input type="file" name="CardVideo" accept=".mp4" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label class="control-label">Before Example Image</label>
                <input type="file" name="BeforeExampleImage" accept=".jpg, .jpeg, .png" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label class="control-label">After Example Image</label>
                <input type="file" name="AfterExampleImage" accept=".jpg, .jpeg, .png" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoursesStore/Views/Courses/Delete.cshtml
@model CoursesStore.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <input type="submit" value="Back"asp-action="Index" class="btn btn-link"></input>
    </form>
</div>

CoursesStore/Views/Courses/Details.cshtml
@model CoursesStore.Models.Course

@{
    ViewData["Title"] = "Details";
}

<style>
    main {
        background-color: #161a1e;
    }
</style>

<div class="card border-0" style="background-color: #161a1e">
    <video id="videoPlayer" src="~/Graphics/Course/@Model.Name/MainVideo.mp4" muted loop autoplay class="card-img" style="max-height: 44vw; object-fit: cover;"></video>
    <div class="card-img-overlay h-75 text-light container d-flex flex-column justify-content-center video-items-div">
        <h1 class="fw-bold pt-5 display-6 text-center BLOCKBUSTER-EFFECTS-tag">@Model.Name.ToUpper() @LangLocalizer["PROJECT EFFECTS PACK"]<br>@LangLocalizer["FOR FILMMAKERS"]</h1>
    </div>
</div>

<div class="row" style="margin: 10% 0% 10% 0%; color: #e2e3ea">
    <div class="m-auto p-1" style="max-width: 700px;">
        <div class="">
            <div class="row g-0">
                <div class="col-md-7 text-center d-flex align-items-center justify-content-center">
                    <video src="~/Graphics/Course/@Model.Name/CardVideo.mp4" muted loop autoplay class="card-img" style="width: 100%;"></video>
                </div>
                <div class="col-md-5">
                    <div class="card-body" style="margin-left: 5%;">
                        <h1 class="card-text">@Model.Name</h1>
                        <h2>@Model.Price $</h2>
                        <a class="btn btn-outline-danger btn-lg w-50" asp-controller="Courses" asp-action="PurchaseCreate" asp-route-id="@Model.Id" role="button" style="margin-bottom: 5%;">@LangLocalizer["Buy"]</a>
                        <p class="card-text"><b>@LangLocalizer["Description:"] </b>@Model.Description</p>
                        <p class="card-text"><b>@LangLocalizer["Effects count:"] </b>@Model.EffectCount</p>
                        <p class="card-text">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="color: #e2e3ea; margin: 10% 0% 10% 0%;">
    <div class="container-fluid text-center m-auto p-3">
        <h1>@Model.Name.ToUpper() @LangLocalizer["EFFECTS EXAMPLES"]</h1>
    </div>
    <div class="row g-0 text-center m-auto p-5">
        <div id="before-after-slider">
            <div id="before-image">
                <img src="~/Graphics/Course/@Model.Name/BeforeExample.png" alt="before"/>
            </div>
            <div id="after-image">
                <img src="~/Graphics/Course/@Model.Name/AfterExample.png" alt="After"/>
            </div>
            <div id="resizer"></div>
        </div>
    </div>
</div>

<div style="color: #e2e3ea; margin: 10% 0% 5% 0%;">
    <div class="container-fluid text-center m-auto p-3">
        <h1>In which programs this set of effects can be used:</h1>
    </div>
    <div class="row g-0 text-center m-auto p-5">
        <div class="col-md-6 text-center m-auto">
            <ul style="font-size: 1.1rem; font-weight: bold;">
                <li class="mb-2">ADOBE PREMIERE PRO</li>
                <li class="mb-2">AFTER EFFECTS</li>
                <li class="mb-2">FINAL CUT PRO</li>
                <li class="mb-2">DAVINCI RESOLVE</li>
                <li class="mb-2">HITFILM EXPRESS</li>
                <li class="mb-2">VEGAS PRO</li>
            </ul>
        </div>
        <div class="col-md-6 text-center m-auto" id="bubleModel" style="height: 400px;">

        </div>
    </div>
</div>

<div class="accordion accordion-flush col-md-7 m-auto p-5" id="accordionFlushExample">
    <h2 style="color: #e2e3ea;">FAQ</h2>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                @LangLocalizer["How do I Use the Overlays?"]
            </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
                <p>                    
                    @LangLocalizer["To use overlays, simply import them into your video software the same way you import any video footage. Then place the selected overlay above your shot in your timeline."]
                </p>
                <p>
                    @LangLocalizer["To get rid of the black background, simply change the blending mode of the selected overlay. Every video software has a blending mode option (the blending mode is basically how two layers are blended with each other). Use the Screen blending mode to get the best results."]
                </p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                @LangLocalizer["Do Overlays work with my Video Software?"]
            </button>
        </h2>
        <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
                <p>
                    @LangLocalizer["Overlays works with almost every video software available on the market. Our overlays are MOV and MP4 files compressed with a Prores codec, which makes them almost universally compatible. Keep in mind, that our pack is made to be used on a computer. But It is also designed to be used with your mobile phone or tablet."]
                </p>
                <p>
                    @LangLocalizer["If you're working with Adobe Premier Pro, Final Cut Pro, Adobe After Effects, DaVinci Resolve, Sony Vegas Pro, or even mobile soft like Alight Motion, Kine Master, CapCut and other - overlays pack will work perfectly with your software."]
                </p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                @LangLocalizer["Can I Purchase vfx pack with my Mobile Phone?"]
            </button>
        </h2>
        <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
                <p>
                    @LangLocalizer["Of course. You can buy the product using your mobile phone or your tablet and download it later on your computer. We send a permanent link to your email address so you can download the product anytime. But remember that each package is designed to be used on a specific device. You won't be able to use the effects for a PC on a mobile phone or tablet."]
                </p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingFour">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
                @LangLocalizer["How do I Use the Sound Assets?"]
            </button>
        </h2>
        <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
                <p>
                    @LangLocalizer["To use the sound assets, simply import the WAV or MP3 files into your editing software the same way you import any video/audio media. Then place the selected audio asset below your shot in your timeline in the dedicated audio track."]
                </p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingFive">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFive" aria-expanded="false" aria-controls="flush-collapseFive">
                @LangLocalizer["What hardware would be optimal for the job?"]
            </button>
        </h2>
        <div id="flush-collapseFive" class="accordion-collapse collapse" aria-labelledby="flush-headingFive" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
                <p>
                    @LangLocalizer["Windows 10/Apple macOS 10.12"]
                </p>
                <p>
                    @LangLocalizer["Processor: Intel Core i5/i7, Amd FX/Ryzen"]
                </p>
                <p>
                    @LangLocalizer["RAM: 8 GB"]
                </p>
                <p>
                    @LangLocalizer["Video card: Nvidia or AMD with 4 GB of video memory."]
                </p>
            </div>
        </div>
    </div>
</div>






@*<script>
    const video = document.getElementById('videoPlayer');
    const playButton = document.getElementById('playButton');
    const pauseButton = document.getElementById('pauseButton');

    playButton.addEventListener('click', function () {
        video.play();
        playButton.style.display = 'none';
        pauseButton.style.display = 'inline';
    });

    pauseButton.addEventListener('click', function () {
        video.pause();
        pauseButton.style.display = 'none';
        playButton.style.display = 'inline';
    });
</script>*@

CoursesStore/Views/Courses/Index.cshtml
@model IEnumerable<CoursesStore.Models.Course>
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = "List of Courses";
}

<body style="">
   
    <div class="card text-bg-dark border-0">
        <video src="~/Graphics/Design/videoplayback.mp4" muted autoplay loop class="card-img rounded-0"></video>
        <div class="card-img-overlay h-75 text-light container d-flex flex-column justify-content-center video-items-div">
            <h2 class="fw-bold pt-5 display-6 text-center BLOCKBUSTER-EFFECTS-tag">@LangLocalizer["BLOCKBUSTER EFFECTS"]<br>@LangLocalizer["FOR FILMMAKERS"]</h2>
            <div class="buttons d-flex justify-content-center">
                <a class="btn btn-outline-light btn-lg" href="#" role="button">@LangLocalizer["Make Order"]</a>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 py-5">
            @foreach (var item in Model)
            {
                <div class="col">
                    <div class="card shadow-sm card-hover">
                        <div class="row g-0">
                            <div class="col-md-12">
                                <div class="card-header text-white bg-dark">
                                    <p class="card-text">
                                        <h5 class="card-title">
                                            @item.Name
                                            @if (User.Identity.IsAuthenticated)
                                            {
                                                <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                            }
                                        </h5>
                                    </p>    
                                </div>
                            </div>
                            <div class="card-hover">
                                <div class="image-container">
                                    <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.Id">
                                        <img src="~/Graphics/Course/@item.Name/PreviewImage.png" class="img-fluid" alt="Name">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>

CoursesStore/Views/Courses/PurchaseCreate.cshtml
@model CoursesStore.Models.CoursePurchaseVM

@{
    ViewData["Title"] = "Purchase";
}

<div class="wrapper" style="margin: 5% 0% 5% 0%;">
    <div class="checkout container">
        @Html.HiddenFor(n => n.Id)
        <div class="container row g-0 m-auto p-4 buy-product-info-div">
            <div class="col-md-8 p-2" style="font-size: 16px;">
                <h3 class="card-title p-2" name="Title" asp-for="@Model.Name">@Model.Name</h3>
                <h5 class="card-text p-2">@Model.Description</h5>
                <h5 class="card-text p-2">Effect Count: @Model.EffectCount</h5>
                <h5 class="card-text p-2">Price: @Model.Price</h5>
            </div>
            <div class="col-md-4 buy-img-div">
                @{
                    string imageName = @Model.Name.Replace(" ", "_");
                }
                <img src="~/Graphics/Course/@Model.Name/PreviewImage.png" class="img-fluid buy-img" width="100%" alt="Name">
            </div>
        </div>
        <form id="payment-form" method="post" asp-controller="Courses" asp-action="OrderProcessing">
            @Html.HiddenFor(n => n.Id)
            @Html.HiddenFor(n => n.Name)
            @Html.HiddenFor(n => n.Description)
            @Html.HiddenFor(n => n.EffectCount)
            @Html.HiddenFor(n => n.Price)
            <section>
                <div class="bt-drop-in-wrapper">
                    <div id="bt-dropin"></div>
                </div>
            </section>
            @Html.HiddenFor(n => n.Nonce, new { @id = "nonce" })
            <hr />
            <div class="form-group mb-3">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" required/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button class="btn btn-success" type="submit"><span>Confirm payment - $@Model.Price</span></button>
        </form>
    </div>
</div>

<script src="https://js.braintreegateway.com/web/dropin/1.22.0/js/dropin.min.js"></script>
<script>
    var client_token = "@ViewBag.ClientToken";
    var form = document.querySelector('#payment-form');

    braintree.dropin.create({
        authorization: client_token,
        container: '#bt-dropin'
    }, function (createErr, instance) {
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            instance.requestPaymentMethod(function (err, payload) {
                if (err) {
                    return;
                }

                document.querySelector('#nonce').value = payload.nonce;
                form.submit();
            });
        });
    });
</script>

CoursesStore/Views/Courses/PurchaseFailure.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CoursesStore/Views/Courses/PurchaseSuccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}